alias cdj="cd ~/repos/juno"
alias cdsd="cd ~/repos/stardust"
alias gri="git rebase -i "
alias gpf="git push --no-verify -f"
alias kugres="kubectl exec -it postgresql-juno-0 bash"
alias kuju="kubectl exec -it juno-0 sh"
alias cdsl="cd ~/repos/skylab"
alias cdxp="cd ~/repos/ex_pulsar"
alias phx="iex -S mix phx.server"
alias cash="cd ~/repos/cash-accounts"
alias v='nvim'
alias dc="docker-compose"
alias nvim-init="nvim ~/.config/nvim/init.vim"
alias tmux-conif="nvim ~/.tmux.conf"
alias zsh-config="nvim ~/.zshrc"
alias t_dev='tmux attach -t dev'
alias :q=exit
alias mt="mix test --trace --only "
alias xenv='export $(cat .env | xargs)'
alias cd_tst_css= 'cd ~/Library/Application Support/Firefox/Profiles'
alias vnotes='nvim ~/Documents/notes'
alias dbcash='psql -U postgres -h localhost -p 5432 cash_accounts'
alias proto='cd ~/repos/elixir_divvy_protobuf'
alias vproto='nvim ~/repos/elixir_divvy_protobuf'
alias eproto='cd ~/repos/elixir_divvy_protobuf'
alias veproto='nvim ~/repos/elixir_divvy_protobuf'

# iex command history
export ERL_AFLAGS="-kernel shell_history enabled"
